- name: packages | install packages
  become: true
  dnf:
    name: "{{ item }}"
    state: latest
  loop: "{{ software_packages_common_present }}"
  when: software_packages_common_present is defined
  tags: common, software

