- name: workstation setup | download Brave Browser GPG Key
  get_url:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
    mode: '0644'

- name: workstation setup | add Brave repository
  ansible.builtin.shell: |
        echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main" | tee /etc/apt/sources.list.d/brave-browser-release.list

- name: workstation setup | update apt cache due to Brave
  apt:
    update_cache: yes

- name: workstation setup | install Brave Browser
  apt:
    name: brave-browser
    state: present