- name: htpc setup | Copy the flex-launcher .deb file to the target system
  copy:
    src: apps/flex-launcher_2.1_amd64.deb
    dest: /tmp/flex-launcher_2.1_amd64.deb

- name: htpc setup | Install the flex-launcher package
  apt:
    deb: /tmp/flex-launcher_2.1_amd64.deb
    state: present


