
# common dependencies and updates
- include_tasks: software/flatpak_setup.yml
- include_tasks: software/packages_update.yml

# Common package installation
- include_tasks: software/packages_apt.yml
- include_tasks: software/packages_pip.yml

# Common system setup tasks
- include_tasks: system_setup/security_updates.yml
- include_tasks: system_setup/gsettings.yml

# Common apt cleanup tasks
- include_tasks: system_setup/apt_cleanup.yml

