
- block:
  # Flatpak dependencies and remote hubs
  - import_tasks: software/flatpak_setup.yml

  # Packages Update & Upgrade related tasks
  - import_tasks: software/packages_update.yml

  # Common package installation
  - import_tasks: software/packages_apt.yml

  # Common security update tasks
  - import_tasks: system_setup/security_updates.yml

  # Common apt cleanup tasks
  - import_tasks: system_setup/apt_cleanup.yml