- name: system setup | common packages | install packages
  apt:
    name: "{{ software_packages_common_present }}"
    state: present
  when: software_packages_common_present is defined
  tags: common, software