- name: users | ensure groups are present
  become: true
  group:
    name: "{{ item }}"
    state: present
  loop: "{{ htpc_groups }}"
  when: htpc_groups is defined

- name: users | ensure htpc user is present
  become: true
  user:
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    groups: "{{ item.groups | join(',') }}"
    shell: "{{ item.shell }}"
    home: "{{ item.home }}"
  loop: "{{ htpc_users }}"
  when: htpc_users is defined
