# Install Workstation Specific Coprs
- import_tasks: applications/coprs.yml

# Install Workstation Specific Applications
- import_tasks: applications/packages.yml

# Install Workspace Specific Flatpaks
- import_tasks: applications/flatpaks.yml
