---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - htop
        - keepass2
        - notepadqq
        - remmina

  - name: cleanup package cache
    apt:
      autoclean: yes

  - name: autoremove orphan packages
    apt:
      autoremove: yes
