version: '3'

services:
  app:
    container_name: ${PROXY_NAME}
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ${PROXY_DATA_STORAGE}:/data
      - ${PROXY_SSL_STORAGE}:/etc/letsencrypt
    networks:
      - reverse_proxy_network

networks:
  reverse_proxy_network:
    name: reverse_proxy_network
    external: true
