software_packages_common_present:
  - ansible
  - btop
  - curl
  - duf
  - fzf
  - git
  - gparted
  - htop
  - ncdu
  - neovim
  - rsync
  - timeshift
  - tmux
  - vim
  - vlc
  - wget
  - zsh

software_packages_common_absent:
  - akregator
  - dragon
  - elisa
  - kaddressbook
  - kmail
  - kontakt
  - neochat
