- name: flatpaks | install flatpaks
  become: true
  flatpak:
    name: "{{ item }}"
    state: latest
  loop: "{{ flatpaks_htpc_present }}"
  when: flatpaks_htpc_present is defined
  tags: htpc, flatpaks
