- name: system setup | Update apt cache if needed
  apt:
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time }}"
  tags: all, common

- name: system setup | Upgrade packages
  apt:
    upgrade: dist
  when: upgrade_packages
  tags: all, common
