- name: htpc setup | Ensure correct password for htpc main user
  user:
    name: "{{ htpc_main_user }}"
    password: "{{ htpc_main_user_password | password_hash('sha512') }}"
    shell: /bin/bash
    update_password: always

- name: htpc setup | create directories for {{ htpc_main_user }}
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ htpc_main_user }}"
    group: "{{ htpc_main_user }}"
    mode: '0755'
  with_items:
    - /home/{{ htpc_main_user }}/.config/autostart
    - /home/{{ htpc_main_user }}/.config/flex-launcher/

# .config files
# - name: htpc setup | copy flex-launcher config.ini to {{ htpc_main_user }} .config
#   copy:
#     src: files/configs/flex-launcher/config.ini
#     dest: /home/{{ htpc_main_user }}/.config/flex-launcher/config.ini
#     owner: "{{ htpc_main_user }}"
#     group: "{{ htpc_main_user }}"
#     mode: '0755'

- name: htpc setup | flex-launcher | deploy config.ini template
  template:
    src: templates/flex-launcher/config.ini.j2
    dest: /home/{{ htpc_main_user }}/.config/flex-launcher/config.ini
    owner: "{{ htpc_main_user }}"
    group: "{{ htpc_main_user }}"
    mode: '0755'

- name: htpc setup | flex-launcher | copy .desktop to autostart directory
  copy:
    src: files/configs/flex-launcher/flex-launcher.desktop
    dest: /home/{{ htpc_main_user }}/.config/autostart/flex-launcher.desktop
    owner: "{{ htpc_main_user }}"
    group: "{{ htpc_main_user }}"
    mode: '0755'

- name: htpc setup | flex-launcher | copy firefox icon to assets
  copy:
    src: files/configs/flex-launcher/firefox.png
    dest: /usr/share/flex-launcher/assets/icons/firefox.png

# /usr/share/applications
- name: htpc setup | copy retroarch.desktop to /usr/share/applications
  copy:
    src: files/configs/retroarch/retroarch.desktop
    dest: /usr/share/applications/retroarch.desktop
    owner: root
    group: root
    mode: '0644'

- name: htpc setup | copy kodi.desktop to /usr/share/applications
  copy:
    src: files/configs/kodi/kodi.desktop
    dest: /usr/share/applications/kodi.desktop
    owner: root
    group: root
    mode: '0644'


- name: htpc setup | set main user dock applications
  become: yes
  become_user: "{{ htpc_main_user }}"
  community.general.dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: "['pop-cosmic-launcher.desktop', 'pop-cosmic-applications.desktop', 'flex-launcher.desktop', 'firefox.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Terminal.desktop', 'gnome-control-center.desktop']"
    state: present
  
